services:
    turbosms:
        alias: avator_turbosms.turbosms

    avator_turbosms.turbosms:
        class: AVATOR\TurbosmsBundle\Service\Turbosms
        arguments: ["@doctrine.orm.entity_manager", "@translator", "@service_container"]
